import type { SpeciesName } from '../types'

export type Px = [number, number]

export type Species = {
  // Terminal art: three rows, `{f}` is where the 3-character face goes.
  ascii: [string, string, string]
  // Desktop art: a 16×16 grid, one palette letter per pixel ('.' is empty).
  rows: string[]
  palette: Record<string, string>
  eyes: [Px, Px]
  mouth: Px
  // Ink for the eyes and mouth; dark by default.
  eyeColor?: string
  isBeak?: boolean
  isWideMouth?: boolean
  // Only hatches as a legendary, and every legendary is one of these.
  isLegendary?: boolean
}

// An 8-character row is the left half of a symmetric row, mirrored to make 16; a 16-character row is used as is.
const art = (...rows: string[]) => rows.map(r => (r.length === 8 ? r + [...r].reverse().join('') : r))

const EYES: [Px, Px] = [[5, 8], [10, 8]]
const MOUTH: Px = [7, 10]
const _ = '........'

// Most species share this standing body; rows 11–15.
const LEGS = ['...obbll', '..obblll', '..obblll', '...obbo.', '...oooo.']

export const SPECIES = {
  dog: {
    ascii: ['  ___  ', 'U({f})U', ' (_u_)~'],
    rows: art(
      _,
      _,
      _,
      _,
      '.....ooo',
      '..aoobbb',
      '.aaobbbb',
      '.aaobbbb',
      '.aaobbbb',
      '..aobbln',
      '...obbll',
      '...obbbbbbbbo.o.',
      '..obbllllllbbobo',
      '..obbllllllbbo..',
      '...obbo..obbo...',
      '...oooo..oooo...'),
    palette: { o: '#6e4220', b: '#e3a85e', l: '#f8e2c0', a: '#9a5a2c', n: '#2b1d14' },
    eyes: EYES, mouth: MOUTH,
  },
  cat: {
    ascii: [' /\\_/\\ ', '( {f} )', ' (")_)~'],
    rows: art(
      _,
      _,
      '..o.....',
      '..oo....',
      '..oaoooo',
      '..obbbbd',
      '..obbdbd',
      '..obbbbb',
      '.obbbbbb',
      'wobbbbll',
      '..obbbbl',
      '...obbbbbbbbo..o',
      '..obbllllllbbo.o',
      '..obbllllllbboo.',
      '...obbo..obbo...',
      '...oooo..oooo...'),
    palette: { o: '#454a57', b: '#a3aab6', l: '#e6e9ee', a: '#f4a7b9', d: '#6c7383', w: '#c9ced8' },
    eyes: EYES, mouth: MOUTH,
  },
  fox: {
    ascii: [' /\\_/\\ ', '<({f})>', '  \\v/~~'],
    rows: art(_,
      '..a.....',
      '..aa....',
      '..oba...',
      '..obbooo',
      '..obbbbb',
      '.obbbbbb',
      '.obbbbbb',
      '.obbbbbb',
      '.ollbbba',
      '..olllll',
      '...oolllllloo.o.',
      '..obbllllllbbobo',
      '..obbllllllbbolo',
      '...oaao..oaao.o.',
      '...oooo..oooo...'),
    palette: { o: '#7c3410', b: '#f28a3a', l: '#fff4e8', a: '#2b1a12' },
    eyes: EYES, mouth: MOUTH,
  },
  redpanda: {
    ascii: [' (\\_/) ', '=({f})=', ' (_ _)~'],
    rows: art(
      _,
      _,
      '..oo....',
      '.olbo...',
      '.olboooo',
      '..obbbbb',
      '..obblbb',
      '.obbbbbb',
      '.obbbbbb',
      '.ollbbll',
      '..olllll',
      '...oaaaaaaaao.oo',
      '..obaaaaaaaabobs',
      '..obaaaaaaaaboso',
      '...oaao..oaao.oo',
      '...oooo..oooo...'),
    palette: { o: '#3b1d10', b: '#b8481f', l: '#f7efe6', a: '#5a2414', s: '#e6a774' },
    eyes: EYES, mouth: MOUTH,
  },
  cow: {
    ascii: ['  ^__^ ', ' ({f}) ', '  (oo) '],
    rows: art(
      _,
      '....h......h....',
      '....hh....hh....',
      '....oooooooo....',
      'oo.obbbbaaabo.oo',
      'oaaobbbbaaaboaao',
      '.ooobbbbbaabooo.',
      '...obbbbbbbbo...',
      '...obbbbbbbbo...',
      '..ollllllllllo..',
      '..olnllllllnlo..',
      '..ollllllllllo..',
      '...oolllllloo...',
      '..obbaabbbbbbo..',
      '...obbo..obbo...',
      '...oaao..oaao...'),
    palette: { o: '#3a3a3a', b: '#fafafa', l: '#f5b5c3', a: '#2b2b2b', h: '#e8d8a8', n: '#a8606e' },
    eyes: EYES, mouth: [7, 11], isWideMouth: true,
  },
  monkey: {
    ascii: [' .-"-. ', 'o({f})o', '  /_\\_@'],
    rows: art(
      _,
      _,
      _,
      _,
      '.....ooo',
      '...oobbb',
      '..obbbbb',
      'oaobllbb',
      'oaobllll',
      '.oobllll',
      '..obllll',
      '...obbbbbbbbo...',
      '..obbllllllbboo.',
      '..obbllllllbbo.o',
      '...obbo..obbo.o.',
      '...oooo..oooo.oo'),
    palette: { o: '#4a2c17', b: '#8b5a2b', l: '#ebc79c', a: '#d9a07a' },
    eyes: EYES, mouth: MOUTH,
  },
  pufferfish: {
    ascii: [' ,^^^, ', '<({f})<', " `vvv' "],
    rows: art(_, _,
      '...o..o.',
      '....oooo',
      '..oobbbb',
      '.obbbbbb',
      'oobbbbbb',
      'aobbbbbb',
      'aobbbbbb',
      'oobbbbbb',
      '.obbllll',
      '.ollllll',
      '..olllll',
      '...ooooo',
      '...o..o.',
      _),
    palette: { o: '#8a6a10', b: '#f7d046', l: '#fff4bf', a: '#f08a2c' },
    eyes: EYES, mouth: MOUTH,
  },
  otter: {
    ascii: [' .---. ', '( {f} )', '-(___)-'],
    rows: art(_, _, _,
      '..oo....',
      '.oaooooo',
      '..obbbbb',
      '.obbbbbb',
      '.obbbbbb',
      '.obbbbbb',
      'wobbllln',
      '..olllll',
      '...oblll',
      '..obllll',
      '..obllll',
      '...obbo.',
      '...oooo.'),
    palette: { o: '#4a3322', b: '#8c6446', l: '#ead6c0', a: '#c99c78', n: '#2b1d14', w: '#d8c2a8' },
    eyes: EYES, mouth: MOUTH,
  },
  ghost: {
    ascii: ['  .-.  ', ' ({f}) ', '  \\/\\/ '],
    rows: art(_, _, _,
      '.....ooo',
      '...oobbb',
      '..obbbbb',
      '.obbbbbb',
      '.obbbbbb',
      '.obbbbbb',
      'oobbbbbb',
      '.obbbbbb',
      '.obbbbbb',
      '.obbbbbb',
      '.obobbob',
      '.o.o..o.',
      _),
    palette: { o: '#8f93b8', b: '#f3f4ff', l: '#ffffff', a: '#c9b8ff' },
    eyes: EYES, mouth: MOUTH,
  },
  robot: {
    ascii: ['  _A_  ', ' [{f}] ', ' /|=|\\ '],
    rows: art(
      '.......a',
      '.......o',
      '.......o',
      '...ooooo',
      '..obbbbb',
      'aaobssss',
      '.oobssss',
      '..obssss',
      '..obssss',
      '..obssss',
      '..obbbbb',
      '...ooooo',
      '..obllla',
      '..obllll',
      '...obbo.',
      '...oooo.'),
    palette: { o: '#4f5d6b', b: '#a9b7c4', l: '#dfe7ee', a: '#ff6b5a', s: '#14202b' },
    eyes: EYES, mouth: [7, 9], eyeColor: '#69f0ae',
  },
  skull: {
    ascii: [' .---. ', '( {f} )', ' |vvv| '],
    rows: art(
      _,
      _,
      _,
      '....oooo',
      '..oobbbb',
      '.obbbbbb',
      '.obbdddb',
      '.obbdddb',
      '.obbdddb',
      '..obbbbd',
      '..obbbbb',
      '...obaba',
      '....oooo',
      _,
      _,
      _),
    palette: { o: '#5e5a52', b: '#f1ece0', l: '#e2dccb', a: '#bdb49c', d: '#2a2730' },
    eyes: EYES, mouth: MOUTH, eyeColor: '#7cf3ff', isLegendary: true,
  },
  dragon: {
    ascii: ['/\\_^_/\\', '>({f})<', ' /vvv\\~'],
    rows: art(_,
      '...a....',
      '...ao...',
      '...aoooa',
      '..obbbbb',
      'o.obbbbb',
      'wwobbbbb',
      'wwobbbbb',
      'wwobbbbb',
      'w.obblll',
      '..olllll',
      '...oblll',
      '..obllll',
      '..obllll',
      '...oaao.',
      '...oooo.'),
    palette: { o: '#1f4d3a', b: '#3fae6a', l: '#d2f2a8', a: '#f2c14e', w: '#2c7d55' },
    eyes: EYES, mouth: MOUTH, isLegendary: true,
  },
  slime: {
    ascii: [' ,---. ', '( {f} )', "`~~~~~'"],
    rows: art(
      _,
      _,
      _,
      _,
      _,
      '......oo',
      '....oobb',
      '...obbbb',
      '..obwbbbbbbbbo..',
      '.obwbbbbbbbbbbo.',
      'obbbbbbb',
      'obbbbbbb',
      'obbbbbbb',
      'obbbbbbb',
      '.ooooooo',
      _),
    palette: { o: '#2f7a3a', b: '#72d36d', l: '#c8f5b0', w: '#effff0' },
    eyes: [[5, 10], [10, 10]], mouth: [7, 12],
  },
  duck: {
    ascii: ['   __  ', ' <({f})', '  (___)'],
    rows: art(_, _,
      '........ooo.....',
      '.....ooo',
      '....obbb',
      '...obbbb',
      '...obbbb',
      '...obbbb',
      '...obbbb',
      '...obbbb',
      '..oobbbb',
      '.obbbbbb',
      'obbbbbbb',
      'obblllbb',
      '.obbbbbb',
      '..oooooo'),
    palette: { o: '#b07d12', b: '#ffd83d', l: '#ffeea0', a: '#ff8a1c' },
    eyes: EYES, mouth: MOUTH, isBeak: true,
  },
  capybara: {
    ascii: [' n___n ', ' ({f}) ', ' (___) '],
    rows: art(
      _,
      _,
      _,
      '...oo...',
      '..oaoooo',
      '.obbbbbb',
      '.obbbbbb',
      '.obbbbbb',
      '.obbbbbb',
      '.obbllla',
      '.obbllll',
      '..oooooo',
      '..obbbbb',
      '..obbbbb',
      '...obbo.',
      '...oooo.'),
    palette: { o: '#4a3220', b: '#a6743f', l: '#bf8a58', a: '#3a2616' },
    eyes: EYES, mouth: MOUTH,
  },
  octopus: {
    ascii: [' .---. ', '( {f} )', '/(/|\\)\\'],
    rows: art(
      _,
      _,
      _,
      '.....ooo',
      '...oobbb',
      '..obbbbb',
      '..obbbbb',
      '.obbbbbb',
      '.obbbbbb',
      '.obbbbbb',
      '.obbbbbb',
      '..obbbbb',
      'obbobbob',
      'ob.ob.ob',
      '.o..o..o',
      _),
    palette: { o: '#6b2d5c', b: '#d65db1', l: '#f7b2dd' },
    eyes: [[5, 9], [10, 9]], mouth: [7, 11],
  },
  bat: {
    ascii: ['/\\   /\\', '\\({f})/', '  "v"  '],
    rows: art(_,
      '...o....',
      '...oo...',
      '...olo..',
      '...olboo',
      'o..obbbb',
      'oo.obbbb',
      'owoobbbb',
      'owwobbbb',
      'owwobbbb',
      'ow.obbbb',
      'o...obal',
      '...oblll',
      '....obll',
      '....oooo',
      _),
    palette: { o: '#2a1f3d', b: '#5d4b7d', l: '#a491c8', a: '#ffffff', w: '#3f3159' },
    eyes: EYES, mouth: MOUTH,
  },
  mushroom: {
    ascii: [' .-o-. ', '(_o_o_)', ' ({f}) '],
    rows: art(_, _, _,
      '....oooo',
      '..oobbbb',
      '.oblbbbb',
      'obllbbll',
      'obbbbbll',
      'oaaaaaaa',
      '...ossss',
      '..osssss',
      '..osssss',
      '..osssss',
      '..osssss',
      '...oaaaa',
      '....oooo'),
    palette: { o: '#7a1f1f', b: '#e8443a', l: '#fff6e8', a: '#e6d2b0', s: '#fff1dc' },
    eyes: [[5, 11], [10, 11]], mouth: [7, 13],
  },
} satisfies Record<SpeciesName, Species>
