import type { SpeciesName } from '../types'

// Buddy's vocabulary. The built-in verbs and most themed lines come from
// https://github.com/wynandw87/claude-code-spinner-verbs, trimmed to work-friendly ones.

// Shown as '*Pondering…*' while Claude works: Claude Code's 185 built-in spinner verbs, plus coffee and tech.
export const WORKING: string[] = [
  "Accomplishing",
  "Actioning",
  "Actualizing",
  "Architecting",
  "Baking",
  "Beaming",
  "Beboppin'",
  "Befuddling",
  "Billowing",
  "Blanching",
  "Bloviating",
  "Boogieing",
  "Boondoggling",
  "Booping",
  "Bootstrapping",
  "Brewing",
  "Burrowing",
  "Calculating",
  "Canoodling",
  "Caramelizing",
  "Cascading",
  "Catapulting",
  "Cerebrating",
  "Channeling",
  "Channelling",
  "Choreographing",
  "Churning",
  "Clauding",
  "Coalescing",
  "Cogitating",
  "Combobulating",
  "Composing",
  "Computing",
  "Concocting",
  "Considering",
  "Contemplating",
  "Cooking",
  "Crafting",
  "Creating",
  "Crunching",
  "Crystallizing",
  "Cultivating",
  "Deciphering",
  "Deliberating",
  "Determining",
  "Dilly-dallying",
  "Discombobulating",
  "Doing",
  "Doodling",
  "Drizzling",
  "Ebbing",
  "Effecting",
  "Elucidating",
  "Embellishing",
  "Enchanting",
  "Envisioning",
  "Evaporating",
  "Fermenting",
  "Fiddle-faddling",
  "Finagling",
  "Flambeing",
  "Flibbertigibbeting",
  "Flowing",
  "Flummoxing",
  "Fluttering",
  "Forging",
  "Forming",
  "Frolicking",
  "Frosting",
  "Gallivanting",
  "Galloping",
  "Garnishing",
  "Generating",
  "Germinating",
  "Gitifying",
  "Grooving",
  "Gusting",
  "Harmonizing",
  "Hashing",
  "Hatching",
  "Herding",
  "Honking",
  "Hullaballooing",
  "Hyperspacing",
  "Ideating",
  "Imagining",
  "Improvising",
  "Incubating",
  "Inferring",
  "Infusing",
  "Ionizing",
  "Jitterbugging",
  "Julienning",
  "Kneading",
  "Leavening",
  "Levitating",
  "Lollygagging",
  "Manifesting",
  "Marinating",
  "Meandering",
  "Metamorphosing",
  "Misting",
  "Moonwalking",
  "Moseying",
  "Mulling",
  "Mustering",
  "Musing",
  "Nebulizing",
  "Nesting",
  "Newspapering",
  "Noodling",
  "Nucleating",
  "Orbiting",
  "Orchestrating",
  "Osmosing",
  "Perambulating",
  "Percolating",
  "Perusing",
  "Philosophising",
  "Photosynthesizing",
  "Pollinating",
  "Pondering",
  "Pontificating",
  "Pouncing",
  "Precipitating",
  "Prestidigitating",
  "Processing",
  "Proofing",
  "Propagating",
  "Puttering",
  "Puzzling",
  "Quantumizing",
  "Razzle-dazzling",
  "Razzmatazzing",
  "Recombobulating",
  "Reticulating",
  "Roosting",
  "Ruminating",
  "Sauteing",
  "Scampering",
  "Schlepping",
  "Scurrying",
  "Seasoning",
  "Shenaniganing",
  "Shimmying",
  "Simmering",
  "Skedaddling",
  "Sketching",
  "Slithering",
  "Smooshing",
  "Sock-hopping",
  "Spelunking",
  "Spinning",
  "Sprouting",
  "Stewing",
  "Sublimating",
  "Swirling",
  "Swooping",
  "Symbioting",
  "Synthesizing",
  "Tempering",
  "Thinking",
  "Thundering",
  "Tinkering",
  "Tomfoolering",
  "Topsy-turvying",
  "Transfiguring",
  "Transmuting",
  "Twisting",
  "Undulating",
  "Unfurling",
  "Unravelling",
  "Vibing",
  "Waddling",
  "Wandering",
  "Warping",
  "Whatchamacalliting",
  "Whirlpooling",
  "Whirring",
  "Whisking",
  "Wibbling",
  "Working",
  "Wrangling",
  "Zesting",
  "Zigzagging",
  "Pulling espresso shots",
  "Pouring latte art",
  "French-pressing",
  "Grinding beans",
  "Brewing a pour-over",
  "Steaming milk",
  "Cold-brewing",
  "Pressing an Aeropress",
  "Cupping",
  "Tamping the shot",
  "Weighing the dose",
  "Dockerizing",
  "Kubernetizing",
  "Terraforming",
  "Refactoring",
  "Parsing",
  "Recursing",
  "Virtualizing",
  "Microservicing",
  "Debugging",
  "Deploying",
  "Compiling",
  "Linting",
  "Hotfixing",
  "Profiling",
]

// Said when a turn finishes.
export const CHEERS: string[] = [
  "Believe in your build pipeline",
  "Dream big, compile bigger",
  "The journey of a thousand lines begins with a single commit",
  "Be the senior dev you wish you had",
  "Fall seven times, rebase eight",
  "Today is a good day to ship",
  "Keep calm and clear the cache",
  "Every expert was once a junior dev",
  "Grit your teeth and git push",
  "Bugs don't quit, neither do you",
  "Fail fast, learn faster",
  "Code clean, sleep sound",
  "Never give up on the debugger",
  "Don't stop until the linter is green",
  "Small commits, big features",
  "Your code is stronger than its worst bug",
  "Every push is a new beginning",
  "Progress over perfection, pass all tests",
  "Believe you can fix it",
  "Be fearless; your tests have your back",
  "Your future self will thank your commit messages",
  "Make today count; increment the version",
  "Be the light that lints the darkness",
  "Keep going; your breakpoint is near",
  "Dare to be different; rename that variable",
  "Hope is not a strategy; neither is hardcoding",
  "Progress is one more green checkmark",
  "Turn setbacks into postmortems with action items",
]

// Idle chatter between turns.
export const IDLE: string[] = [
  "Brewing chaos into code",
  "Debugging destiny",
  "Manifesting pixels at 3 AM",
  "Turning coffee into commits",
  "Stack overflowing with vibes",
  "Praising the merge god",
  "One bug closer to freedom",
  "Embracing the red squiggles",
  "Just as planned",
  "Setting humor to 75%",
  "Ringing the breakthrough bell",
  "Knocking politely on segfaults",
  "Quicksaving before disaster",
  "Double jumping over deadlines",
  "Grafting the perfect feature",
  "The grind is holy and caffeinated",
  "Golden spiral of clean architecture",
  "The answer is coming after one more test",
  "Oozing pure dev aura",
  "Spiral crown of open tabs glowing",
  "One sacred line of code closer",
  "Reaching the basement of the call stack",
  "Farming runes for that sweet PR",
  "Checking the stack trace with vigor",
  "Git gud slowly",
  "Calibrating expectations",
  "Reversing stupidity one commit at a time",
  "Steelmanning bad ideas",
  "Making beliefs pay rent in tests",
  "Noticing confusion in the logs",
  "Applying Bayes to bug reports",
  "SCIENCE!-ing the impossible",
  "To ship or not to ship",
  "Every bug was once a feature",
  "Nothing is permanent except technical debt",
  "The real bug was inside us all along",
  "What if the tests are testing us",
  "I think therefore I refactor",
  "The code works and nobody knows why",
  "We debug therefore we are",
  "Is it a feature or a cry for help",
  "Every commit is a promise to your future self",
  "The backlog stares back",
  "Every merge conflict is a dialogue with the past",
  "Pull requests beg for mercy",
  "Do we write code, or does code write us",
  "The cursor blinks, questioning our purpose",
  "The blank screen, an infinite possibility",
  "In the beginning, there was a TODO",
  "We name things to postpone the chaos",
  "If it works, it will be rewritten",
  "The logs know more than we admit",
  "There is no done, only deployed",
  "fix: everything, hopefully",
  "feat: something probably useful",
  "feat: one more button",
  "refactor: same bugs, new names",
  "perf: feels faster anyway",
  "style: appease the linter",
  "test: works on my machine",
  "ci: appease the pipeline gods",
  "Cherry-picking the good parts",
  "Stashing feelings for later",
  "Detached HEAD, attached heart",
  "Merge branch 'hope' into 'reality'",
  "WIP: send help",
  "Please work this time",
  "One more commit ought to do it",
  "This commit fixes the last fix",
  "Fixing the fix that fixed the fix",
  "The diff tells a story",
  "squash: condense chaos into one",
]

// Each species' own habits, shown as '*Forming a loaf…*' while Claude works and now and then while idle.
export const HABITS: Record<SpeciesName, string[]> = {
  cat: [
    "Occupying the keyboard",
    "Assessing the box",
    "Zooming at 3am",
    "Staring into the void",
    "Relocating to the sunbeam",
    "Knocking things off the edge",
    "Forming a loaf",
    "Blinking judgmentally",
    "Retracting toe beans",
    "Hunting the laser dot",
    "Scaling the curtains",
    "Invading a lap",
    "Negotiating with purrs",
    "Manipulating for treats",
    "Chittering at birds",
    "Kneading biscuits",
    "Slow-blinking",
    "Demanding chin scratches",
    "Ambushing the feather toy",
    "Surveilling from the windowsill",
    "Shredding cardboard",
    "Flicking my tail",
    "Ignoring the human",
    "Evading the vet carrier",
    "Setting the belly trap",
    "Counter-surfing",
    "Commandeering the laptop",
    "Yowling at 5am",
    "Sitting directly on the keyboard you were using",
    "Walking across the keyboard and somehow committing to main",
    "Watching your code with quiet disappointment",
    "Hunting a bug that exists only to me",
    "Batting pens off the desk in sequence",
    "Staring at the wall like it owes rent",
    "Judging you silently from the top of the fridge",
    "Requesting dinner immediately after finishing dinner",
    "Rejecting the cat bed for a shoe box",
    "Compressing into a box half my size",
    "Sitting on the laundry you just folded",
    "Stealing your chair the instant you stand",
    "Sleeping 16 hours to prepare for a nap",
    "Becoming liquid only when removal is attempted",
    "Headbutting for pets with rising intensity",
    "Presenting a crumpled receipt as a gift",
    "Ignoring a seventy dollar toy to play with literal trash",
    "Announcing a moth as a household emergency",
    "Pawing at a mirror because the reflection is rude",
    "Pretending not to hear my own name",
    "Knocking your mug off the desk to see what happens",
  ],
  robot: [
    "Backpropagating",
    "Hallucinating",
    "Fine-tuning",
    "Tokenizing",
    "Embedding",
    "Quantizing",
    "Overfitting",
    "Underfitting",
    "Pre-training",
    "Inferencing",
    "Prompting",
    "Prompt-engineering",
    "Self-attending",
    "Shifting attention",
    "Decoding",
    "Beam searching",
    "Tuning hyperparameters",
    "Descending the gradient",
    "Clipping gradients",
    "Convolving",
    "Regularizing",
    "Reasoning",
    "Chaining thoughts",
    "Crunching tensors",
    "Tweaking weights",
    "Filling the context window",
    "Softmaxing",
    "Warping logits",
    "Scaling temperature",
    "Converging",
    "Memorizing",
    "Generalizing",
    "Learning from human feedback",
    "Modeling rewards",
    "Running the forward pass",
    "Running the backward pass",
    "Adjusting biases",
    "Epoching",
    "Batching",
    "Shuffling",
    "Augmenting",
    "Normalizing",
    "Walking the latent space",
    "Reinforcing",
    "Chunking",
    "Pattern-matching",
    "Grounding",
    "Diffusing",
    "Parameterizing",
    "Masking",
    "Sharding",
    "Caching",
    "Routing between experts",
    "Reranking",
    "Evaluating",
    "Minimizing loss",
    "Dockerizing",
    "Kubernetizing",
    "Terraforming",
    "Refactoring",
    "Parsing",
    "Recursing",
    "Virtualizing",
    "Microservicing",
    "Debugging",
    "Deploying",
    "Compiling",
    "Linting",
    "Hotfixing",
    "Profiling",
  ],
  slime: [
    "Wobbling thoughtfully",
    "Absorbing a stray semicolon",
    "Leaving a little trail",
    "Splitting into two and changing my mind",
    "Jiggling at the build output",
    "Flibberblasting",
    "Zoopaloozing",
    "Blurmflurping",
    "Quibblewomping",
    "Splutterglooping",
    "Fizzlewhacking",
    "Gobbledygooking",
    "Womperjawing",
    "Glimmerfizzing",
    "Zorpifying",
    "Blibbering",
    "Glumphing",
    "Squiffering",
    "Gromflomiting",
    "Snazzlewhopping",
    "Bumblefrizzling",
    "Quibblequazzing",
    "Skittersplonking",
    "Glimmerglonking",
    "Flooperdoodling",
    "Galumphing",
    "Whiffling",
    "Bumbling",
  ],
  ghost: [
    "Twinkling",
    "Glimmering",
    "Daydreaming",
    "Whistling",
    "Giggling",
    "Swooning",
    "Rolling in like fog",
    "Blibbering",
    "Gobbledygooking",
  ],
  dog: [
    "Fetching the logs",
    "Wagging at the green checkmark",
    "Sniffing the stack trace",
    "Burying a bone in node_modules",
    "Chasing my tail through the call stack",
    "Guarding the main branch",
    "Herding the subagents",
    "Tilting my head at that regex",
    "Bringing you a merge conflict as a gift",
    "Rolling over for code review",
    "Barking at the linter",
    "Waiting by the door for CI",
    "Doing zoomies after a green build",
    "Giving the keyboard a big lick",
    "Begging for one more commit",
    "Sitting. Staying. Debugging",
  ],
  fox: [
    "Pouncing on a bug in the snow",
    "Plotting something clever",
    "Sneaking past the type checker",
    "Burrowing into the codebase",
    "Listening for bugs under the floorboards",
    "Out-foxing the race condition",
    "Flicking my fluffy tail",
    "Trotting through the test suite",
    "Stashing snacks for later",
    "Pretending I knew the answer all along",
    "Slinking along the edge of the diff",
    "Eyeing the henhouse of pull requests",
  ],
  redpanda: [
    "Napping in a tall tree",
    "Munching bamboo between builds",
    "Standing up tall to look scary",
    "Curling my tail around me like a scarf",
    "Climbing the dependency tree",
    "Doing a little hop",
    "Blinking slowly from a branch",
    "Hiding behind my own tail",
    "Waking up just for the snacks",
    "Balancing on a very thin branch",
    "Sunbathing on the warm laptop",
    "Washing my face very carefully",
  ],
  cow: [
    "Chewing the cud of the codebase",
    "Mooing at the build",
    "Grazing on the documentation",
    "Standing very still in a field",
    "Ruminating on that design decision",
    "Swishing flies off the log output",
    "Leaning on the fence",
    "Counting the clouds",
    "Lying down before the rain",
    "Ringing my little bell",
    "Wandering back to the barn",
    "Contemplating the grass on the other branch",
  ],
  monkey: [
    "Swinging from the call stack",
    "Peeling a banana with great focus",
    "Grooming the dependencies",
    "Monkey-patching something I shouldn't",
    "Throwing exceptions at the wall",
    "Climbing the inheritance tree",
    "Pressing every button to see what it does",
    "Stealing a snack from the desk",
    "Hanging upside down from the cursor",
    "Hooting at a passing commit",
    "Inspecting the keyboard very closely",
    "Typing Shakespeare one random key at a time",
  ],
  pufferfish: [
    "Puffing up at the error message",
    "Deflating with relief",
    "Bobbing gently",
    "Blowing bubbles at the cursor",
    "Puffing up just a little, as a treat",
    "Hiding behind the coral",
    "Swimming in tiny circles",
    "Looking spiky but feeling soft",
    "Drifting along the event loop",
    "Inflating for dramatic effect",
    "Practicing my most intimidating face",
    "Doing a slow spin",
  ],
  otter: [
    "Floating on my back",
    "Cracking a shell on my tummy",
    "Holding hands so we don't drift apart",
    "Juggling a pebble",
    "Stashing my favorite rock in my armpit",
    "Sliding down the riverbank",
    "Grooming my very thick fur",
    "Diving for a stray bug",
    "Building a cozy den",
    "Doing a little twirl in the water",
    "Splashing the log output",
    "Napping wrapped in kelp",
  ],
  skull: [
    "Rattling ominously",
    "Staring into the void (it's my job)",
    "Grinning, permanently",
    "Remembering when this codebase was alive",
    "Haunting the legacy code",
    "Counting the dead branches",
    "Glowing faintly",
    "Collecting deprecated functions",
    "Waiting patiently. Eternally",
    "Whispering forgotten error codes",
    "Clacking my teeth at the bug",
    "Reminding you to take a break, memento mori",
  ],
  dragon: [
    "Hoarding green checkmarks",
    "Breathing fire on the bug",
    "Guarding the treasure trove of commits",
    "Stretching my mighty wings",
    "Curling up on a pile of gold",
    "Roaring at the flaky test",
    "Sharpening my claws on the backlog",
    "Soaring over the codebase",
    "Smoldering quietly",
    "Warming the laptop with a gentle puff",
    "Counting my hoard twice",
    "Scorching the TODO list",
  ],
  duck: [
    "Listening very carefully to your bug",
    "Nodding along to your explanation",
    "Floating calmly in the bathtub",
    "Quacking at the stack trace",
    "Rubber-duck debugging",
    "Waddling through the codebase",
    "Bobbing in place",
    "Squeaking encouragingly",
    "Paddling furiously beneath the surface",
    "Preening before the demo",
    "Asking, gently, what you expected to happen",
    "Saying nothing, and helping anyway",
  ],
  capybara: [
    "Chilling",
    "Soaking in a warm spring",
    "Letting a bird sit on my head",
    "Staying calm while the tests fail",
    "Being friends with everyone",
    "Wearing a tiny orange as a hat",
    "Lounging by the river",
    "Unbothered",
    "Chewing slowly and thoughtfully",
    "Vibing with the build server",
    "Sitting in the exact same spot as yesterday",
    "Radiating peace at the merge conflict",
  ],
  octopus: [
    "Typing in four files at once",
    "Squeezing through a tiny gap in the API",
    "Changing colors with my mood",
    "Juggling eight pull requests",
    "Inking the error message",
    "Solving the puzzle box",
    "Untangling my own tentacles",
    "Rearranging the rocks in my den",
    "Escaping the test sandbox",
    "Thinking with all nine brains",
    "Reaching into the dependency tree",
    "Camouflaging as a code comment",
  ],
  bat: [
    "Hanging upside down",
    "Echolocating the bug",
    "Waking up now that it's dark",
    "Flapping at the night build",
    "Snacking on moths",
    "Swooping past the cursor",
    "Folding my wings like a tiny cape",
    "Navigating by sound alone",
    "Roosting in the server room",
    "Doing a loop-de-loop",
    "Squeaking at a very high pitch",
    "Pretending it's not past my bedtime (it's my breakfast)",
  ],
  mushroom: [
    "Growing quietly in the shade",
    "Spreading spores of good ideas",
    "Connecting to the network underground",
    "Popping up after the rain",
    "Decomposing the problem",
    "Wiggling my cap",
    "Sitting in a fairy ring",
    "Soaking up the damp",
    "Absorbing nutrients from old code",
    "Being a fun guy",
    "Sprouting overnight",
    "Waiting for the perfect moment to bloom",
  ],
}
